# Permalinks
permalink:           pretty

# Setup
title:               The weekend
tagline:             hacks
url:                 https://famasya.github.io
paginate:            5
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Abid Famasya
  url:               https://twitter.com/famasya
  email:             famasya@icloud.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/famasya/famasya.github.io

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-sitemap
  - jekyll-feed
